name: Publish
on:
  # push:
  #   paths-ignore:
  #     - "**.md"
  #   tags:
  #     - 'v*'
  push:
    branches:
        - main

  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  
  Publish:
    runs-on: ubuntu-latest
    env:
      name: pypi
      url: https://pypi.org/p/discord-ext-ipcx

    permissions:
      id-token: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish Packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
    

      
      